.TH "C:/Users/Vinushan/Documents/University/2nd Year/IMAT2912/labcode/CW/CW1_starter/include/blockCircleContactListener.h" 3 "Mon Feb 22 2021" "Box2D CW1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Vinushan/Documents/University/2nd Year/IMAT2912/labcode/CW/CW1_starter/include/blockCircleContactListener.h
.SH SYNOPSIS
.br
.PP
\fC#include <Box2D\\Box2D\&.h>\fP
.br
\fC#include 'dynamicCircle\&.h'\fP
.br
\fC#include 'dynamicBlock\&.h'\fP
.br
\fC#include 'staticBlock\&.h'\fP
.br
\fC#include 'staticSensor\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBlockCircleContactListener\fP"
.br
.RI "A listener which listens for contacts between balls and blocks and changes block colours\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Box2D CW1 from the source code\&.
