.TH "BlockCircleContactListener" 3 "Mon Feb 22 2021" "Box2D CW1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockCircleContactListener \- A listener which listens for contacts between balls and blocks and changes block colours\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <blockCircleContactListener\&.h>\fP
.PP
Inherits b2ContactListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBBeginContact\fP (b2Contact *contact)"
.br
.RI "Called when two fixtures begin to touch\&. "
.ti -1c
.RI "void \fBEndContact\fP (b2Contact *contact)"
.br
.RI "Called when two fixtures cease to touch\&. "
.in -1c
.SH "Detailed Description"
.PP 
A listener which listens for contacts between balls and blocks and changes block colours\&. 
.PP
Definition at line 17 of file blockCircleContactListener\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Box2D CW1 from the source code\&.
