.TH "C:/Users/vinus/Documents/University/2nd Year/IMAT2912/labcode/CW/CW1_starter Directory Reference" 3 "Fri Apr 30 2021" "Lab Book 3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/vinus/Documents/University/2nd Year/IMAT2912/labcode/CW/CW1_starter Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBinclude\fP"
.br
.ti -1c
.RI "directory \fBsrc\fP"
.br
.in -1c
