.TH "doorPressureSensor" 3 "Fri Apr 30 2021" "Lab Book 3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doorPressureSensor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <doorPressureSensor\&.h>\fP
.PP
Inherits \fBStaticSensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdoorPressureSensor\fP ()"
.br
.ti -1c
.RI "\fBdoorPressureSensor\fP (b2World *world, sf::Vector2f position, sf::Vector2f size, float orientation, \fBSlidingDoor\fP *door)"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "void \fBonAction\fP (b2Body *other)"
.br
.RI "Thing the sensor does when hit\&. "
.ti -1c
.RI "void \fBoffAction\fP (b2Body *other)"
.br
.RI "Thing the sensor does when hit stops\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSlidingDoor\fP * \fBm_door\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file doorPressureSensor\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "doorPressureSensor::doorPressureSensor ()\fC [inline]\fP"

.PP
Definition at line 13 of file doorPressureSensor\&.h\&.
.SS "doorPressureSensor::doorPressureSensor (b2World * world, sf::Vector2f position, sf::Vector2f size, float orientation, \fBSlidingDoor\fP * door)"

.PP
Default constructor\&. 
.PP
Definition at line 3 of file doorPressureSensor\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void doorPressureSensor::offAction (b2Body * other)\fC [virtual]\fP"

.PP
Thing the sensor does when hit stops\&. 
.PP
Implements \fBStaticSensor\fP\&.
.PP
Definition at line 16 of file doorPressureSensor\&.cpp\&.
.SS "void doorPressureSensor::onAction (b2Body * other)\fC [virtual]\fP"

.PP
Thing the sensor does when hit\&. 
.PP
Implements \fBStaticSensor\fP\&.
.PP
Definition at line 10 of file doorPressureSensor\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSlidingDoor\fP* doorPressureSensor::m_door"

.PP
Definition at line 17 of file doorPressureSensor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab Book 3 from the source code\&.
