.TH "C:/Users/vinus/Documents/University/2nd Year/IMAT2912/labcode/CW/CW1_starter/include/doorPressureSensor.h" 3 "Fri Apr 30 2021" "Lab Book 3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/vinus/Documents/University/2nd Year/IMAT2912/labcode/CW/CW1_starter/include/doorPressureSensor.h
.SH SYNOPSIS
.br
.PP
\fC#include 'staticSensor\&.h'\fP
.br
\fC#include 'slidingDoor\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdoorPressureSensor\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Lab Book 3 from the source code\&.
