.TH "C:/Users/vinus/Documents/University/2nd Year/IMAT2912/labcode/CW/CW1_starter/src/dynamicPendulum.cpp" 3 "Fri Apr 30 2021" "Lab Book 3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/vinus/Documents/University/2nd Year/IMAT2912/labcode/CW/CW1_starter/src/dynamicPendulum.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'dynamicPendulum\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab Book 3 from the source code\&.
