.TH "C:/Users/vinus/Documents/University/2nd Year/IMAT2912/labcode/CW/CW1_starter/include/dynamicBlock.h" 3 "Fri Apr 30 2021" "Lab Book 3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/vinus/Documents/University/2nd Year/IMAT2912/labcode/CW/CW1_starter/include/dynamicBlock.h
.SH SYNOPSIS
.br
.PP
\fC#include <Box2D/Box2D\&.h>\fP
.br
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include 'physicalThing\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDynamicBlock\fP"
.br
.RI "A simple block which can move, rotate and collide with stuff\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Lab Book 3 from the source code\&.
