.TH "C:/Users/vinus/Documents/University/2nd Year/IMAT2912/labcode/CW/CW1_starter/src/main.cpp" 3 "Fri Apr 30 2021" "Lab Book 3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/vinus/Documents/University/2nd Year/IMAT2912/labcode/CW/CW1_starter/src/main.cpp \- Contains the entry point for the application\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <Box2D/Box2D\&.h>\fP
.br
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include 'game\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains the entry point for the application\&. 


.PP
Definition in file \fBmain\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "void main ()"
Entry point for the application 
.PP
Definition at line 12 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lab Book 3 from the source code\&.
