.TH "C:/Users/vinus/Documents/University/2nd Year/IMAT2912/labcode/CW/CW1_starter/include/physicalThing.h" 3 "Fri Apr 30 2021" "Lab Book 3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/vinus/Documents/University/2nd Year/IMAT2912/labcode/CW/CW1_starter/include/physicalThing.h
.SH SYNOPSIS
.br
.PP
\fC#include <Box2D/Box2D\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhysicalThing\fP"
.br
.RI "A simple class with common attributes and a few const values used in a few places\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEG2RAD\fP   0\&.017453f"
.br
.ti -1c
.RI "#define \fBRAD2DEG\fP   57\&.29577f"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEG2RAD   0\&.017453f"

.PP
Definition at line 9 of file physicalThing\&.h\&.
.SS "#define RAD2DEG   57\&.29577f"

.PP
Definition at line 10 of file physicalThing\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lab Book 3 from the source code\&.
