.TH "Ray" 3 "Fri Apr 30 2021" "Lab Book 3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ray
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ray\&.h>\fP
.PP
Inherits sf::Drawable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRay\fP ()"
.br
.ti -1c
.RI "\fBRay\fP (b2World *world, float maxLength, sf::Color colour)"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "void \fBdraw\fP (sf::RenderTarget &target, sf::RenderStates states) const"
.br
.ti -1c
.RI "void \fBcast\fP (sf::Vector2f start)"
.br
.RI "Cast the ray\&. "
.ti -1c
.RI "void \fBsetDirection\fP (float direction)"
.br
.RI "Set ray direction\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file ray\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Ray::Ray ()\fC [inline]\fP"

.PP
Definition at line 14 of file ray\&.h\&.
.SS "Ray::Ray (b2World * world, float maxLength, sf::Color colour)"

.PP
Default constructor\&. Full constructor 
.PP
Definition at line 3 of file ray\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Ray::cast (sf::Vector2f start)"

.PP
Cast the ray\&. 
.PP
Definition at line 21 of file ray\&.cpp\&.
.SS "void Ray::draw (sf::RenderTarget & target, sf::RenderStates states) const"

.PP
Definition at line 16 of file ray\&.cpp\&.
.SS "void Ray::setDirection (float direction)"

.PP
Set ray direction\&. 
.PP
Definition at line 59 of file ray\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab Book 3 from the source code\&.
