.TH "C:/Users/vinus/Documents/University/2nd Year/IMAT2912/labcode/CW/CW1_starter/include/SensorContactListener.h" 3 "Fri Apr 30 2021" "Lab Book 3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/vinus/Documents/University/2nd Year/IMAT2912/labcode/CW/CW1_starter/include/SensorContactListener.h
.SH SYNOPSIS
.br
.PP
\fC#include <Box2D\\Box2D\&.h>\fP
.br
\fC#include 'dynamicCircle\&.h'\fP
.br
\fC#include 'dynamicBlock\&.h'\fP
.br
\fC#include 'staticBlock\&.h'\fP
.br
\fC#include 'staticSensor\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSensorContactListener\fP"
.br
.RI "A listener which listens for contacts between games objects and sensors\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Lab Book 3 from the source code\&.
