.TH "StaticBlock" 3 "Fri Apr 30 2021" "Lab Book 3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StaticBlock \- A simple block which can not move or rotate but can collide with stuff\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <staticBlock\&.h>\fP
.PP
Inherits sf::RectangleShape, and \fBPhysicalThing\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStaticBlock\fP (b2World *world, const sf::Vector2f &position, const sf::Vector2f &size, const float &orientation)"
.br
.RI "Complete contructor\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A simple block which can not move or rotate but can collide with stuff\&. 
.PP
Definition at line 16 of file staticBlock\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StaticBlock::StaticBlock (b2World * world, const sf::Vector2f & position, const sf::Vector2f & size, const float & orientation)"

.PP
Complete contructor\&. 
.PP
Definition at line 7 of file staticBlock\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab Book 3 from the source code\&.
