.TH "C:/Users/vinus/Documents/Careers/Portfolio/DispatchTable/cmake/Fighter.h" 3 "Double Linked List" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/vinus/Documents/Careers/Portfolio/DispatchTable/cmake/Fighter.h
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFighter\fP"
.br
.RI "Base class \fBFighter\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Double Linked List from the source code\&.
