.TH "C:/Users/vinus/Documents/Careers/Portfolio/DispatchTable/cmake/Player.h" 3 "Double Linked List" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/vinus/Documents/Careers/Portfolio/DispatchTable/cmake/Player.h
.SH SYNOPSIS
.br
.PP
\fR#include 'Fighter\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlayer\fP"
.br
.RI "\fBPlayer\fP class is derived from base class \fBFighter\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Double Linked List from the source code\&.
